# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:

#  phpadmin:
#    image: 'phpmyadmin/phpmyadmin:latest'
#    environment:
#      - PMA_HOST=mariadb
#      - PMA_PORT=3306
#      - PMA_USER=bn_opencart
#    ports:
#      - '192.168.0.8:${PHPADMIN_PORT}:8880'
#      - '192.168.0.8:8888:8888'

  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_opencart
      - MARIADB_DATABASE=bitnami_opencart
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    ports:
      - '192.168.0.8:${MARIADB_PORT}:3306'
      - '192.168.0.8:3307:3307'

  opencart:
    image: docker.io/bitnami/opencart:3
    ports:
      - '192.168.0.8:${OPENCART_PORT}:8080'
      - '192.168.0.8:8081:8081'
      # '192.168.0.8:443:8443'
    environment:
      - OPENCART_HOST=${LOCAL_IP}:${OPENCART_PORT}
      - OPENCART_HOST=192.168.0.8
      - OPENCART_DATABASE_HOST=mariadb
      - OPENCART_DATABASE_PORT_NUMBER=3306
      - OPENCART_DATABASE_USER=bn_opencart
      - OPENCART_DATABASE_NAME=bitnami_opencart
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'opencart_data:/bitnami/opencart'
      - 'opencart_storage_data:/bitnami/opencart_storage/'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  opencart_data:
    driver: local
  opencart_storage_data:
    driver: local